### ISSUE TITLE
What is tileLevel in tiled images URL?

### ISSUE THREAD

**Issue by atultiwari** [lovasoa/dezoom.sh#1]
Hi,

First of all congrats for release of this script. It's near perfect now. After some tries I faced 2 issues (will ask 2nd one separately)

After trying this new script on the same URL that you suggested yesterday, I was still facing errors. 
URL with parameters :- 
`./dezoom.sh 189 105 "http://122.160.116.48/DSStore/code/tileHandler.ashx?Id=19110&imageId=-1&tierIndex=0&tileLevel=1&tilePositionX=%X&tilePositionY=%Y&contentType=image/jpeg&isCropped=1"`

Final image rendered was as follows (115 MB) -

![screenshot 64](https://cloud.githubusercontent.com/assets/586934/20935703/dd3a28d4-bc05-11e6-80cc-f06ded07ff84.png)

Note the dead black space, plus on zooming I was not able to appreciate the cellular morphology on zooming (which is a must thing in case of reading pathology slides)

Error log for this image rendering is pasted [here ](https://gist.github.com/atultiwari/8d5961652b90b1c69bedc9591f89b247) (its huge), which basically says this error with different x, y positions -

```
Failed to download 'http://122.160.116.48/DSStore/code/tileHandler.ashx?Id=19110&imageId=-1&tierIndex=0&tileLevel=1&tilePositionX=122&tilePositionY=1&contentType=image/jpeg&isCropped=1'
Failed to download 'http://122.160.116.48/DSStore/code/tileHandler.ashx?Id=19110&imageId=-1&tierIndex=0&tileLevel=1&tilePositionX=166&tilePositionY=1&contentType=image/jpeg&isCropped=1'

```
Since I myself had seen that bottom right tile's X, Y positions are 189 & 105. So I compared the URL, and found out that in the above mentioned URL `tileLevel` was set to `1`, while in network browser it was `0` for these X, Y positions. (I know, I myself had posted URL with `tileLevel=1` in [this ](https://github.com/lovasoa/dezoomify/issues/108) issue thread, but links with `tileLevel=1` are also being shown in network browser).

So, when I retried with setting `tileLevel=0`, final image (260 MB) is like -
![screenshot 62](https://cloud.githubusercontent.com/assets/586934/20935990/fef983d8-bc06-11e6-91d3-caa188968152.png)

It has its own issue logs (which I will ask in separate thread), but the best part is mostly this was THE IMAGE I wanted to save as offline, because such images were increasing my internet bill exponentially (unfortunately I am on limited bandwidth and these files are very big in size). Best part is I can zoom to the real level, and can read the actual cellular morphology now.

That brings me to the original question - "What is this `tileLevel` and what value should I use in different circumstances?"

Thanks for this wonderful script. Now I am hopeful that I will be able to save some important study related images offline.

**Comment by lovasoa** [comment]
Oh, I am really sorry that you have to pay for your bandwidth! Using my script so many times must have made it incredibly expensive.

> That brings me to the original question - "What is this tileLevel and what value should I use in different circumstances?"

The image is split into several zoom levels (in order for you to be able to see the full image without downloading all tiles). Successive zoom levels have (in your case) smaller and smaller total size.
In order to know what zoom level to use, just use the network inspector in your browser, zoom into the image, and see what zoom level is used for the most zoomed-in tiles.

**Comment by atultiwari** [comment]
Thanks for the info. I think, in my case `tileLevel=0` is for most zoomed-in tiles. I will try it with other microscopic slides images, once a **fix for corrupted jpeg/tile data** is available.

And I am sorry for the mis-understanding. Yes, I am on limited bandwidth, but while using your script, I learnt many new things, which otherwise I would have never learnt about. So, what I think of it is a good investment in learning things.

What I meant was - I am supposed to learn about 700-1000 such microscopic slides in next 3-6 months. For that I  have to daily open that and some other sites. Since there is no official save as offline option, it has increased my daily internet bill. I don't want to move to different site, because this one actually displays really zoomed slides with full length, and unfortunately my hostel doesn't allow me to get some broadband line with unlimited bandwidth. So, I was searching for a way to save these slide images offline, and therefore learnt about your script, which once developed completely (with mentioned feature request), will help me save my internet bills.

**Comment by lovasoa** [comment]
I am currently downloading your image as I have unlimited bandwidth. I will post it here when it's ready.
