### ISSUE TITLE
Part of the image become blank

### ISSUE THREAD

**Issue by Huginn22** [lovasoa/dezoom.sh#10]
Hi, long time no see! :)
I used the script to bash an image, but when it finished, part of the image become blank.
It prompted me that there are some parts failed to download and try it again later. However, I tried it again and again, there still have some blank parts in the image.
![1](https://user-images.githubusercontent.com/19512842/31821364-7c41ce52-b5d7-11e7-94c4-7d5665088258.png)

Source: http://collections.si.edu/search/tag/tagDoc.htm?thumb=true&recordID=chndm_1952-71-2&hlterm=woodcut&inline=true
My command: 
./dezoom.sh -x 0 -y 0 -X 13 -Y 17 "ids.si.edu/ids/viewTile/A/9b5/9b5adb429828fb4cab079d5d680c13f4_files/13/%X_%Y.jpg"

Hoping you could make time for this issue, I really appreciate it. Thank you in advance and have a great day! :) @lovasoa 

By the way, maybe it's a website problem? Because I tested an image of the other site, it worked great like always.

**Comment by zstadler** [comment]
It looks to me like a site issue.

Each invocation downloads only missing tiles and each failure is retried once. As a result, the list of failures is getting shorter in each invocation. 

My 4th invocation was successful despite one temporary failure:
```
$ ./dezoom.sh -x 0 -y 0 -X 13 -Y 17 -o chndm_1952-71-2.jpg "ids.si.edu/ids/viewTile/A/9b5/9b5adb429828fb4cab079d5d680c13f4_files/13/%X_%Y.jpg"
Failed to download 'ids.si.edu/ids/viewTile/A/9b5/9b5adb429828fb4cab079d5d680c13f4_files/13/8_16.jpg'
Assembling tiles... (this can be long)
Tiles successfully assembled in 'chndm_1952-71-2.jpg'```
