### ISSUE TITLE
Batch download?

### ISSUE THREAD

**Issue by itkind** [lovasoa/dezoom.sh#14]
Hi, I like your script. Is there a way to download more than 1 image? lets say about 500?

Thank you!

**Comment by lovasoa** [comment]
It's a bash script, so you can use a simple [bash loop](https://www.cyberciti.biz/faq/bash-for-loop/) if you want. For instance: 

```bash
for image in "image1" "image2" "image3"
do
    ./dezoom.sh -x 0 -y 0 -X 188 -Y 105 "http://example.com/tile.php?image=$image&tilePositionX=%X&tilePositionY=%Y"
done
```
