### ISSUE TITLE
Thank you! 

### ISSUE THREAD

**Issue by itkind** [lovasoa/dezoom.sh#15]
Dear sir, I couldn't find an other way to contact you. I want to thank you for creating this tool. We used it for many projects. Almost our whole text library was only possible because of your tool. 1. https://www.talmud.de/tlmd/tanach/ 2. https://www.talmud.de/tlmd/mischne-tora/

We used and still use your tool to achieve a better OCR result. 
Thank you so much!

**Comment by lovasoa** [comment]
Hello! I'm very happy this tool could help :) 
But have you tried dezoomify-rs ? I do not maintain dezoom.sh anymore, and usually recommend using dezoomify-rs instead, because it supports more image formats, and is easier to install and to use.

**Comment by lovasoa** [comment]
https://dezoomify-rs.ophir.dev/
