### ISSUE TITLE
[Feature Request] Re-download corrupted tiles before making final image

### ISSUE THREAD

**Issue by atultiwari** [lovasoa/dezoom.sh#2]
Hi,

When I used this script, final image (260 MB) is like -
![screenshot 62](https://cloud.githubusercontent.com/assets/586934/20936449/a6a2a424-bc08-11e6-84a9-f9feeb7b94e4.png)

Slight zooming on the corrupted area -
![screenshot 63](https://cloud.githubusercontent.com/assets/586934/20936505/d579f6f8-bc08-11e6-9b1a-d8bceb96640d.png)

I have posted the complete log [here](https://gist.github.com/atultiwari/89fbae5b236a1aad94427986465b5974) on gist, which basically appears to say, error while converting -

```
convert: Corrupt JPEG data: premature end of data segment `/var/folders/hw/jgsyw4_j28v5r129z_c5ryc00000gn/T/tmp.rO1puU6N/tile33_41.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
convert: Invalid JPEG file structure: two SOI markers `/var/folders/hw/jgsyw4_j28v5r129z_c5ryc00000gn/T/tmp.rO1puU6N/tile33_41.jpg' @ warning/jpeg.c/JPEGErrorHandler/319.

```

It appears to me some tiles either not downloaded properly or got corrupted, therefore final image lacks some tiles. So if there is a way to add one more step to re-download the tiles which found to be corrupted or couldn't be downloaded initially before making final image, it would make this script perfect.

Thanks.
Regards,
Atul

**Comment by lovasoa** [comment]
Here is your file: https://mab.to/vxqE4Nc07

**Comment by lovasoa** [comment]
But I think you would actually use less bandwidth by using the scrollable version, and thus loading just the tiles you need. You will never look at all the ~10 000 tiles of all your ~700 files.

**Comment by atultiwari** [comment]
Thank you very much for taking personal interest in this issue. I will check it in the afternoon. (3:15 AM here)

**Comment by atultiwari** [comment]
Yes, I agree, I won't need to look all the tiles. But I being in the learning phase, am not sure which tile to look and which I can ignore. Once I have studied about a particular slide and have once seen all the tiles, then I can decide which tiles I can ignore in future.
