### ISSUE TITLE
How to use the script behind proxy?

### ISSUE THREAD

**Issue by atultiwari** [lovasoa/dezoom.sh#5]
Hi,

I am using `cygwin64` in windows 10. After the addition of new functions in script, it became easier for me to save the images. I wanted to try this script in my college network, but it stuck at downloading 0%. My college network uses proxy `172.16.19.11` and port `80` to connect (no username or password). I have enabled Proxy server from Windows 10 settings.  When I ping google from `cygwin`, I get reply, but when I use the script, it doesn't seem to start. I read [this](http://stackoverflow.com/questions/197904/how-do-i-use-cygwin-behind-the-corporate-firewall) stackoverflow answer -

`export http_proxy=http://username:password@host:port/
`

But, I am unable to figure out, how/where to use this?

Thanks for the heavy customization of script :)
Regards

**Comment by lovasoa** [comment]
Just paste the line to the terminal before launching the script with ./dezoom.sh [...]

If you successfully installed it on windows, maybe you can make a PR to this repo, adding detailed instructions for windows to README.md? That would be very nice of you. 

15 декабря 2016 г. 10:24:14 GMT+03:00, atultiwari <notifications@github.com> пишет:
>Hi,
>
>I am using `cygwin64` in windows 10. After the addition of new
>functions in script, it became easier for me to save the images. I
>wanted to try this script in my college network, but it stuck at
>downloading 0%. My college network uses proxy `172.16.19.11` and port
>`80` to connect (no username or password). I have enabled Proxy server
>from Windows 10 settings.  When I ping google from `cygwin`, I get
>reply, but when I use the script, it doesn't seem to start. I read
>[this](http://stackoverflow.com/questions/197904/how-do-i-use-cygwin-behind-the-corporate-firewall)
>stackoverflow answer -
>
>`export http_proxy=http://username:password@host:port/
>`
>
>But, I am unable to figure out, how/where to use this?
>
>Thanks for the heavy customization of script :)
>Regards
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lovasoa/dezoom.sh/issues/5

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by atultiwari** [comment]
Thank you for your prompt reply. I will try it after 4 hours from now (when I will be in college). After getting success in connecting, I will write README.md later tonight.

**Comment by atultiwari** [comment]
Silly me, the solution was in front of me and I don't know why I didn't even try it. It worked. Thanks. Issue can be closed now.
