### ISSUE TITLE
Cygwin installation in windows

### ISSUE THREAD

**Issue by atultiwari** [lovasoa/dezoom.sh#6]
Do select `wget` and `imagemagick` packages when installing  `cygwin`.

Screenshots -
![1](https://cloud.githubusercontent.com/assets/586934/21268157/93eab9f2-c3d3-11e6-9dc5-df355a68ef80.PNG)
![2](https://cloud.githubusercontent.com/assets/586934/21268159/941ea3de-c3d3-11e6-8c76-8a2f6fc59685.PNG)
![3](https://cloud.githubusercontent.com/assets/586934/21268158/941d3972-c3d3-11e6-9953-ff3c9106a354.PNG)
![4](https://cloud.githubusercontent.com/assets/586934/21268160/9444ca00-c3d3-11e6-9e3b-4e9e070e2d27.PNG)
![5](https://cloud.githubusercontent.com/assets/586934/21268162/944f0416-c3d3-11e6-9345-6e011ca9725d.PNG)
![6](https://cloud.githubusercontent.com/assets/586934/21268161/944d4eb4-c3d3-11e6-8759-e203293d1d6f.PNG)

The screenshots URL from this issue will be taken for Readme file.

**Comment by lovasoa** [comment]
Maybe it would be better to upload the images to [the wiki](https://github.com/lovasoa/dezoom.sh/wiki), and simply add a link to the wiki page in the README ?

**Comment by lovasoa** [comment]
Anyway, thanks a lot for the detailed screenshots !

**Comment by atultiwari** [comment]
hi @lovasoa, yes that would be better, but I was unable to create wiki from my end or add a screenshots folder in your repo directly (this is my very fist attempt to write anything in github except posting issues).

I have updated the Readme file as per my knowledge.  [Link](https://github.com/atultiwari/dezoom.sh/blob/master/README.md). 
I know better would be to convert them into single gif or something like that, as they are occupying so much of space (and these are unnecessary for anyone using mac or linux)

**Comment by atultiwari** [comment]
This was my very first attempt to use pull request and editing features of github. I don't know whether I used them correctly or not. I think I just sent a pull request with updated readme file (I hope that means to merge with your original file)

**Comment by atultiwari** [comment]
I have taken all the necessary screenshots, will try to create new single gif later tonight/tomorrow. I think that would be better.
