### ISSUE TITLE
Images become disorder

### ISSUE THREAD

**Issue by Huginn22** [lovasoa/dezoom.sh#8]
Hi, the Cygwin works this time. However, the image which bashed becomes disorder like that:

http://thumbnail0.baidupcs.com/thumbnail/b75f0ef378b6e55cd0266582db81b9be?fid=3296584357-250528-441227312047964&time=1489824000&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-uXhvOs5apP0yfJnVRjudhy9sWPo%3d&expires=8h&chkbd=0&chkv=0&dp-logid=1778400840606588946&dp-callid=0&size=c10000_u10000&quality=90

I do not know why it became like that. I hope you could tell me how to solve it, thank you. Sorry to bother you again.

**Comment by Huginn22** [comment]
I forgot to say that I tried many times and many different images, but it always end up disorder.

**Comment by Huginn22** [comment]
Excuse me. I'm a little urgent, could you help me with it a little fast? Thank you so much! @lovasoa

**Comment by lovasoa** [comment]
Hi,
 I cannot see the image you linked to. Can you include the image here? 
  Please also provide the full command you typed. 

Ophir
-- 
Простите за краткость, создано в K-9 Mail.

**Comment by Huginn22** [comment]
Could you see it now? 
http://pan.baidu.com/share/link?shareid=2029962391&uk=3296584357

And I typed the command like below:
./dezoom.sh 20 36 "the address of the image%X_%Y.jpg"

**Comment by lovasoa** [comment]
No I can't. Why don't you simply post it here on github? Press "attach file", and choose the file on your computer. 
-- 
Простите за краткость, создано в K-9 Mail.

**Comment by lovasoa** [comment]
And please give the address of the image. 
-- 
Простите за краткость, создано в K-9 Mail.

**Comment by Huginn22** [comment]
I'm so sorry, I'm not so skillful to use GitHub. 
The address of the image: http://image.dpm.org.cn/dyx.html?path=/tilegenerator/dest/files/image/8831/2011/3024/img0005.xml

**Comment by Huginn22** [comment]
I selected the file but it said the file can't be processed... Maybe you could give me an e-mail address then I can post it to you.

**Comment by Huginn22** [comment]
![22](https://cloud.githubusercontent.com/assets/19512842/24129628/dc467ea8-0e1e-11e7-99af-090054d017b5.jpg)

Finally, it worked. Here is the disorder image, and good morning by the way.😄

**Comment by Huginn22** [comment]
![23 1](https://cloud.githubusercontent.com/assets/19512842/24178153/4ba2e0a2-0ee2-11e7-90a8-404352c0db61.jpg)

When it assembles the image, it happens like this. @lovasoa

**Comment by Huginn22** [comment]
![22_20170324133146929](https://cloud.githubusercontent.com/assets/19512842/24281793/542e7a32-1096-11e7-8cdb-ff1859149c81.jpg)

This Image missed the left and up sides, But nothing went wrong while assembling this image. Hoping you could tell me how to fix it. Thanks a lot.
The address of this image: http://image.dpm.org.cn/dyx.html?path=/tilegenerator/dest/files/image/8831/2007/1559/img0012.xml
