### ISSUE TITLE
Failed to download image

### ISSUE THREAD

**Issue by Huginn22** [lovasoa/dezoom.sh#9]
Hi, I used the Cygwin to bash the image, but it failed. I typed the commond as below:
./dezoom.sh -x 0 -y 0 -X 27 -Y 31 "www.emuseum.jp/img/content/100966001001/1/d6/%X_%Y.jpeg"

The address of the image: http://www.emuseum.jp/detail/100966?x=&y=&s=&d_lang=en&s_lang=zh&word=&class=1&title=&c_e=&region=&era=&cptype=&owner=&pos=1&num=3&mode=detail&century=

Hoping you could tell me how to solve it, thanks.
![2](https://cloud.githubusercontent.com/assets/19512842/24597700/e35ac504-1879-11e7-8c4e-701d77467c6e.jpg)

**Comment by Huginn22** [comment]
@lovasoa Looking for your help, please.

**Comment by lovasoa** [comment]
This is because the URL you give is invalid:
http://www.emuseum.jp/img/content/100966001001/1/d6/0_0.jpeg

**Comment by lovasoa** [comment]
Please read the documentation carefully: https://github.com/lovasoa/dezoom.sh#advanced-usage

**Comment by lovasoa** [comment]
In your case, the top left tile is http://www.emuseum.jp/img/content/100966001001/1/d6/1_1.jpeg
so the minimum value of x and y is 1.

So the command to use is:

```
dezoom.sh -x 1 -y 1 -X 27 -Y 31 "www.emuseum.jp/img/content/100966001001/1/d6/%X_%Y.jpeg"
```

**Comment by lovasoa** [comment]
![result-low](https://cloud.githubusercontent.com/assets/552629/24757697/a43b154c-1ae8-11e7-8692-be498ef907cc.jpg)

**Comment by Huginn22** [comment]
Alright, I know what's the problem. I thought ALL the minimum value of x and y should be 0. 
I couldn't thank you more for teaching me so much! Thank you again for bashing the image for me and have a nice day! :)
